// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18408
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Quartz.Features.ManualTune.FeatureFiles
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.IgnoreAttribute()]
    public partial class MultipleFunctionSelectionLiveTunePlotFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "TUN - MET - QRZ - Multiple Function Selection.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Multiple Function Selection (Live Tune Plot)", "In order to display Method Functions within the Live Tune Page Plot\r\nI want to be" +
                    " able to load a prevously saved / created method and check that the expected num" +
                    "ber of m/z functions are available for selection", ProgrammingLanguage.CSharp, new string[] {
                        "ignore"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Multiple Function Selection (Live Tune Plot)")))
            {
                Quartz.Features.ManualTune.FeatureFiles.MultipleFunctionSelectionLiveTunePlotFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 45
#line 46
 testRunner.Given("the browser is opened on the Tune page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        public virtual void MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD(string plotType, string methodType, string lockMass, string functions, string enabled, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MET-MultipleFunctionSelection-01 - Acquisition Create (Non-HD)", exampleTags);
#line 50
this.ScenarioSetup(scenarioInfo);
#line 45
this.FeatureBackground();
#line 51
 testRunner.When(string.Format("an Acquisition \'{0}\' with \'{1}\' is set Recording using Acquisition | Record", methodType, lockMass), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 52
  testRunner.And(string.Format("this Acquisition is viewed during the recording, within the \'{0}\'", plotType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Plot View"});
            table1.AddRow(new string[] {
                        "MZ"});
            table1.AddRow(new string[] {
                        "BPI"});
            table1.AddRow(new string[] {
                        "TIC"});
#line 53
 testRunner.Then(string.Format("the individual \'{0}\' will be \'<Enabled\'> and can be selected within the \'Plot Vie" +
                        "w\' and \'Function 1\' will be selected by default", functions), ((string)(null)), table1, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-01 - Acquisition Create (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods with Lock Mass (Normal Tune Page plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "MS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "Yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MS, 2:MS(LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD_MethodsWithLockMassNormalTunePagePlot_Variant0()
        {
            this.MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD("Tune Page", "MS", "Yes", "1:MS, 2:MS(LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-01 - Acquisition Create (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods with Lock Mass (Normal Tune Page plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "MSMS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "Yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MSMS, 2:MS(LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD_MethodsWithLockMassNormalTunePagePlot_Variant1()
        {
            this.MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD("Tune Page", "MSMS", "Yes", "1:MSMS, 2:MS(LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-01 - Acquisition Create (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods with Lock Mass (Normal Tune Page plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "MSe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "Yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MS(Low CE), 2:MS(High CE), 3:MS(LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD_MethodsWithLockMassNormalTunePagePlot_Variant2()
        {
            this.MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD("Tune Page", "MSe", "Yes", "1:MS(Low CE), 2:MS(High CE), 3:MS(LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-01 - Acquisition Create (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods with Lock Mass (Pop-out Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "MS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "Yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MS, 2:MS(LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD_MethodsWithLockMassPop_OutPlot_Variant0()
        {
            this.MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD("Pop-out", "MS", "Yes", "1:MS, 2:MS(LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-01 - Acquisition Create (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods with Lock Mass (Pop-out Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "MSMS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "Yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MSMS, 2:MS(LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD_MethodsWithLockMassPop_OutPlot_Variant1()
        {
            this.MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD("Pop-out", "MSMS", "Yes", "1:MSMS, 2:MS(LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-01 - Acquisition Create (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods with Lock Mass (Pop-out Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "MSe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "Yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MS(Low CE), 2:MS(High CE), 3:MS(LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD_MethodsWithLockMassPop_OutPlot_Variant2()
        {
            this.MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD("Pop-out", "MSe", "Yes", "1:MS(Low CE), 2:MS(High CE), 3:MS(LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-01 - Acquisition Create (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods without Lock Mass (Normal Tune Page plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "MS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "No")]
        public virtual void MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD_MethodsWithoutLockMassNormalTunePagePlot_Variant0()
        {
            this.MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD("Tune Page", "MS", "No", "1:MS", "No", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-01 - Acquisition Create (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods without Lock Mass (Normal Tune Page plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "MSMS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MSMS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "No")]
        public virtual void MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD_MethodsWithoutLockMassNormalTunePagePlot_Variant1()
        {
            this.MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD("Tune Page", "MSMS", "No", "1:MSMS", "No", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-01 - Acquisition Create (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods without Lock Mass (Normal Tune Page plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "MSe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MS(Low CE), 2:MS(High CE)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD_MethodsWithoutLockMassNormalTunePagePlot_Variant2()
        {
            this.MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD("Tune Page", "MSe", "No", "1:MS(Low CE), 2:MS(High CE)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-01 - Acquisition Create (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods without Lock Mass (Pop-out Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "MS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "No")]
        public virtual void MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD_MethodsWithoutLockMassPop_OutPlot_Variant0()
        {
            this.MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD("Pop-out", "MS", "No", "1:MS", "No", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-01 - Acquisition Create (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods without Lock Mass (Pop-out Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "MSMS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MSMS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "No")]
        public virtual void MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD_MethodsWithoutLockMassPop_OutPlot_Variant1()
        {
            this.MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD("Pop-out", "MSMS", "No", "1:MSMS", "No", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-01 - Acquisition Create (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods without Lock Mass (Pop-out Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "MSe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MS(Low CE), 2:MS(High CE)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD_MethodsWithoutLockMassPop_OutPlot_Variant2()
        {
            this.MET_MultipleFunctionSelection_01_AcquisitionCreateNon_HD("Pop-out", "MSe", "No", "1:MS(Low CE), 2:MS(High CE)", "Yes", ((string[])(null)));
        }
        
        public virtual void MET_MultipleFunctionSelection_02_AcquisitionCreateHD(string plotType, string methodType, string lockMass, string functions, string enabled, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MET-MultipleFunctionSelection-02 - Acquisition Create (HD)", exampleTags);
#line 86
this.ScenarioSetup(scenarioInfo);
#line 45
this.FeatureBackground();
#line 87
 testRunner.When(string.Format("an Acquisition \'{0}\' with \'{1}\' is set Recording using Acquisition | Record", methodType, lockMass), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 88
  testRunner.And(string.Format("this Acquisition is viewed during the recording, within the \'{0}\'", plotType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Plot View"});
            table2.AddRow(new string[] {
                        "MZ"});
            table2.AddRow(new string[] {
                        "BPI"});
            table2.AddRow(new string[] {
                        "TIC"});
#line 89
 testRunner.Then(string.Format("the individual \'{0}\' will be \'<Enabled\'> and can be selected within the \'Plot Vie" +
                        "w\' and \'Function 1\' will be selected by default", functions), ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-02 - Acquisition Create (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods with Lock Mass (Normal Tune Page plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "HD-MS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "Yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:HDMS, 2:MS (LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_02_AcquisitionCreateHD_MethodsWithLockMassNormalTunePagePlot_Variant0()
        {
            this.MET_MultipleFunctionSelection_02_AcquisitionCreateHD("Tune Page", "HD-MS", "Yes", "1:HDMS, 2:MS (LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-02 - Acquisition Create (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods with Lock Mass (Normal Tune Page plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "HD-MSMS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "Yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:HDMSMS, 2:MS (LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_02_AcquisitionCreateHD_MethodsWithLockMassNormalTunePagePlot_Variant1()
        {
            this.MET_MultipleFunctionSelection_02_AcquisitionCreateHD("Tune Page", "HD-MSMS", "Yes", "1:HDMSMS, 2:MS (LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-02 - Acquisition Create (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods with Lock Mass (Normal Tune Page plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "HD-MSe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "Yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:HDMS(Low CE), 2:HDMS(High CE), 3:MS (LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_02_AcquisitionCreateHD_MethodsWithLockMassNormalTunePagePlot_Variant2()
        {
            this.MET_MultipleFunctionSelection_02_AcquisitionCreateHD("Tune Page", "HD-MSe", "Yes", "1:HDMS(Low CE), 2:HDMS(High CE), 3:MS (LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-02 - Acquisition Create (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods with Lock Mass (Pop-out Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "HD-MS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "Yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:HDMS, 2:MS(LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_02_AcquisitionCreateHD_MethodsWithLockMassPop_OutPlot_Variant0()
        {
            this.MET_MultipleFunctionSelection_02_AcquisitionCreateHD("Pop-out", "HD-MS", "Yes", "1:HDMS, 2:MS(LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-02 - Acquisition Create (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods with Lock Mass (Pop-out Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "HD-MSMS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "Yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:HDMSMS, 2:MS(LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_02_AcquisitionCreateHD_MethodsWithLockMassPop_OutPlot_Variant1()
        {
            this.MET_MultipleFunctionSelection_02_AcquisitionCreateHD("Pop-out", "HD-MSMS", "Yes", "1:HDMSMS, 2:MS(LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-02 - Acquisition Create (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods with Lock Mass (Pop-out Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "HD-MSe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "Yes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:HDMS(Low CE), 2:HDMS(High CE), 3:MS(LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_02_AcquisitionCreateHD_MethodsWithLockMassPop_OutPlot_Variant2()
        {
            this.MET_MultipleFunctionSelection_02_AcquisitionCreateHD("Pop-out", "HD-MSe", "Yes", "1:HDMS(Low CE), 2:HDMS(High CE), 3:MS(LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-02 - Acquisition Create (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods without Lock Mass (Normal Tune Page plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "HD-MS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:HDMS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "No")]
        public virtual void MET_MultipleFunctionSelection_02_AcquisitionCreateHD_MethodsWithoutLockMassNormalTunePagePlot_Variant0()
        {
            this.MET_MultipleFunctionSelection_02_AcquisitionCreateHD("Tune Page", "HD-MS", "No", "1:HDMS", "No", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-02 - Acquisition Create (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods without Lock Mass (Normal Tune Page plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "HD-MSMS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:HDMSMS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "No")]
        public virtual void MET_MultipleFunctionSelection_02_AcquisitionCreateHD_MethodsWithoutLockMassNormalTunePagePlot_Variant1()
        {
            this.MET_MultipleFunctionSelection_02_AcquisitionCreateHD("Tune Page", "HD-MSMS", "No", "1:HDMSMS", "No", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-02 - Acquisition Create (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods without Lock Mass (Normal Tune Page plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "HD-MSe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:HDMS(Low CE), 2:HDMS(High CE)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_02_AcquisitionCreateHD_MethodsWithoutLockMassNormalTunePagePlot_Variant2()
        {
            this.MET_MultipleFunctionSelection_02_AcquisitionCreateHD("Tune Page", "HD-MSe", "No", "1:HDMS(Low CE), 2:HDMS(High CE)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-02 - Acquisition Create (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods without Lock Mass (Pop-out Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "HD-MS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:HDMS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "No")]
        public virtual void MET_MultipleFunctionSelection_02_AcquisitionCreateHD_MethodsWithoutLockMassPop_OutPlot_Variant0()
        {
            this.MET_MultipleFunctionSelection_02_AcquisitionCreateHD("Pop-out", "HD-MS", "No", "1:HDMS", "No", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-02 - Acquisition Create (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods without Lock Mass (Pop-out Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "HD-MSMS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:HDMSMS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "No")]
        public virtual void MET_MultipleFunctionSelection_02_AcquisitionCreateHD_MethodsWithoutLockMassPop_OutPlot_Variant1()
        {
            this.MET_MultipleFunctionSelection_02_AcquisitionCreateHD("Pop-out", "HD-MSMS", "No", "1:HDMSMS", "No", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-02 - Acquisition Create (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Methods without Lock Mass (Pop-out Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "HD-MSe")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Lock Mass", "No")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:HDMS(Low CE), 2:HDMS(High CE)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_02_AcquisitionCreateHD_MethodsWithoutLockMassPop_OutPlot_Variant2()
        {
            this.MET_MultipleFunctionSelection_02_AcquisitionCreateHD("Pop-out", "HD-MSe", "No", "1:HDMS(Low CE), 2:HDMS(High CE)", "Yes", ((string[])(null)));
        }
        
        public virtual void MET_MultipleFunctionSelection_03_CustomTuneNon_HD(string plotType, string methodType, string functions, string enabled, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MET-MultipleFunctionSelection-03 - Custom Tune (Non-HD)", exampleTags);
#line 122
this.ScenarioSetup(scenarioInfo);
#line 45
this.FeatureBackground();
#line 123
 testRunner.When(string.Format("an Acquisition \'{0}\' is run using Acquisition | Custom Tune", methodType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 124
  testRunner.And(string.Format("this Acquisition is viewed during the run, within the \'{0}\'", plotType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Plot View"});
            table3.AddRow(new string[] {
                        "MZ"});
            table3.AddRow(new string[] {
                        "BPI"});
            table3.AddRow(new string[] {
                        "TIC"});
#line 125
 testRunner.Then(string.Format("the individual \'{0}\' will be \'<Enabled\'> and can be selected within the \'Plot Vie" +
                        "w\' and \'Function 1\' will be selected by default", functions), ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-03 - Custom Tune (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Normal Tune Page plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "ms.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "No")]
        public virtual void MET_MultipleFunctionSelection_03_CustomTuneNon_HD_ViewedInNormalTunePagePlot_Variant0()
        {
            this.MET_MultipleFunctionSelection_03_CustomTuneNon_HD("Tune Page", "ms.xml", "1:MS", "No", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-03 - Custom Tune (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Normal Tune Page plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "ms_dual_lockmass.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MS, 2:MS(LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_03_CustomTuneNon_HD_ViewedInNormalTunePagePlot_Variant1()
        {
            this.MET_MultipleFunctionSelection_03_CustomTuneNon_HD("Tune Page", "ms_dual_lockmass.xml", "1:MS, 2:MS(LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-03 - Custom Tune (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Normal Tune Page plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "ms_edc.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "No")]
        public virtual void MET_MultipleFunctionSelection_03_CustomTuneNon_HD_ViewedInNormalTunePagePlot_Variant2()
        {
            this.MET_MultipleFunctionSelection_03_CustomTuneNon_HD("Tune Page", "ms_edc.xml", "1:MS", "No", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-03 - Custom Tune (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Normal Tune Page plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "ms_lockmass.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MS, 2:MS(LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_03_CustomTuneNon_HD_ViewedInNormalTunePagePlot_Variant3()
        {
            this.MET_MultipleFunctionSelection_03_CustomTuneNon_HD("Tune Page", "ms_lockmass.xml", "1:MS, 2:MS(LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-03 - Custom Tune (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Normal Tune Page plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "msms.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MSMS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "No")]
        public virtual void MET_MultipleFunctionSelection_03_CustomTuneNon_HD_ViewedInNormalTunePagePlot_Variant4()
        {
            this.MET_MultipleFunctionSelection_03_CustomTuneNon_HD("Tune Page", "msms.xml", "1:MSMS", "No", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-03 - Custom Tune (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Normal Tune Page plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "tune.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:Tune")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "No")]
        public virtual void MET_MultipleFunctionSelection_03_CustomTuneNon_HD_ViewedInNormalTunePagePlot_Variant5()
        {
            this.MET_MultipleFunctionSelection_03_CustomTuneNon_HD("Tune Page", "tune.xml", "1:Tune", "No", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-03 - Custom Tune (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Normal Tune Page plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "TofMRM.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MRM, 2:MRM, 3:MS(LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_03_CustomTuneNon_HD_ViewedInNormalTunePagePlot_Variant6()
        {
            this.MET_MultipleFunctionSelection_03_CustomTuneNon_HD("Tune Page", "TofMRM.xml", "1:MRM, 2:MRM, 3:MS(LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-03 - Custom Tune (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Normal Tune Page plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 7")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "mse.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MS(Low CE), 2:MS(High CE)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_03_CustomTuneNon_HD_ViewedInNormalTunePagePlot_Variant7()
        {
            this.MET_MultipleFunctionSelection_03_CustomTuneNon_HD("Tune Page", "mse.xml", "1:MS(Low CE), 2:MS(High CE)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-03 - Custom Tune (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Normal Tune Page plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "mse_trend")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MS(Low CE), 2:MS(High CE)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_03_CustomTuneNon_HD_ViewedInNormalTunePagePlot_Variant8()
        {
            this.MET_MultipleFunctionSelection_03_CustomTuneNon_HD("Tune Page", "mse_trend", "1:MS(Low CE), 2:MS(High CE)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-03 - Custom Tune (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Pop-out plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "ms.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "No")]
        public virtual void MET_MultipleFunctionSelection_03_CustomTuneNon_HD_ViewedInPop_OutPlot_Variant0()
        {
            this.MET_MultipleFunctionSelection_03_CustomTuneNon_HD("Pop-out", "ms.xml", "1:MS", "No", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-03 - Custom Tune (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Pop-out plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "ms_dual_lockmass.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MS, 2:MS(LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_03_CustomTuneNon_HD_ViewedInPop_OutPlot_Variant1()
        {
            this.MET_MultipleFunctionSelection_03_CustomTuneNon_HD("Pop-out", "ms_dual_lockmass.xml", "1:MS, 2:MS(LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-03 - Custom Tune (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Pop-out plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "ms_edc.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "No")]
        public virtual void MET_MultipleFunctionSelection_03_CustomTuneNon_HD_ViewedInPop_OutPlot_Variant2()
        {
            this.MET_MultipleFunctionSelection_03_CustomTuneNon_HD("Pop-out", "ms_edc.xml", "1:MS", "No", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-03 - Custom Tune (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Pop-out plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "ms_lockmass.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MS, 2:MS(LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_03_CustomTuneNon_HD_ViewedInPop_OutPlot_Variant3()
        {
            this.MET_MultipleFunctionSelection_03_CustomTuneNon_HD("Pop-out", "ms_lockmass.xml", "1:MS, 2:MS(LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-03 - Custom Tune (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Pop-out plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "msms.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MSMS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "No")]
        public virtual void MET_MultipleFunctionSelection_03_CustomTuneNon_HD_ViewedInPop_OutPlot_Variant4()
        {
            this.MET_MultipleFunctionSelection_03_CustomTuneNon_HD("Pop-out", "msms.xml", "1:MSMS", "No", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-03 - Custom Tune (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Pop-out plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 5")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "tune.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:Tune")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "No")]
        public virtual void MET_MultipleFunctionSelection_03_CustomTuneNon_HD_ViewedInPop_OutPlot_Variant5()
        {
            this.MET_MultipleFunctionSelection_03_CustomTuneNon_HD("Pop-out", "tune.xml", "1:Tune", "No", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-03 - Custom Tune (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Pop-out plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 6")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "TofMRM.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MRM, 2:MRM, 3:MS(LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_03_CustomTuneNon_HD_ViewedInPop_OutPlot_Variant6()
        {
            this.MET_MultipleFunctionSelection_03_CustomTuneNon_HD("Pop-out", "TofMRM.xml", "1:MRM, 2:MRM, 3:MS(LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-03 - Custom Tune (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Pop-out plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 7")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "mse.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MS(Low CE), 2:MS(High CE)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_03_CustomTuneNon_HD_ViewedInPop_OutPlot_Variant7()
        {
            this.MET_MultipleFunctionSelection_03_CustomTuneNon_HD("Pop-out", "mse.xml", "1:MS(Low CE), 2:MS(High CE)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-03 - Custom Tune (Non-HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Pop-out plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 8")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "mse_trend")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MS(Low CE), 2:MS(High CE)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_03_CustomTuneNon_HD_ViewedInPop_OutPlot_Variant8()
        {
            this.MET_MultipleFunctionSelection_03_CustomTuneNon_HD("Pop-out", "mse_trend", "1:MS(Low CE), 2:MS(High CE)", "Yes", ((string[])(null)));
        }
        
        public virtual void MET_MultipleFunctionSelection_04_CustomTuneHD(string plotType, string methodType, string functions, string enabled, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MET-MultipleFunctionSelection-04 - Custom Tune (HD)", exampleTags);
#line 158
this.ScenarioSetup(scenarioInfo);
#line 45
this.FeatureBackground();
#line 159
 testRunner.When(string.Format("an Acquisition \'{0}\' is run using Acquisition | Custom Tune", methodType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 160
  testRunner.And(string.Format("this Acquisition is viewed during the run, within the \'{0}\'", plotType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Plot View"});
            table4.AddRow(new string[] {
                        "MZ"});
            table4.AddRow(new string[] {
                        "BPI"});
            table4.AddRow(new string[] {
                        "TIC"});
#line 161
 testRunner.Then(string.Format("the individual \'{0}\' will be \'<Enabled\'> and can be selected within the \'Plot Vie" +
                        "w\' and \'Function 1\' will be selected by default", functions), ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-04 - Custom Tune (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Normal Tune Page plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "hdms.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:HDMS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "No")]
        public virtual void MET_MultipleFunctionSelection_04_CustomTuneHD_ViewedInNormalTunePagePlot_Variant0()
        {
            this.MET_MultipleFunctionSelection_04_CustomTuneHD("Tune Page", "hdms.xml", "1:HDMS", "No", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-04 - Custom Tune (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Normal Tune Page plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "hdmsms.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:HDMSMS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "No")]
        public virtual void MET_MultipleFunctionSelection_04_CustomTuneHD_ViewedInNormalTunePagePlot_Variant1()
        {
            this.MET_MultipleFunctionSelection_04_CustomTuneHD("Tune Page", "hdmsms.xml", "1:HDMSMS", "No", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-04 - Custom Tune (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Normal Tune Page plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "HDMRM.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:HDMRM, 2:HDMRM, 3:MS(LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_04_CustomTuneHD_ViewedInNormalTunePagePlot_Variant2()
        {
            this.MET_MultipleFunctionSelection_04_CustomTuneHD("Tune Page", "HDMRM.xml", "1:HDMRM, 2:HDMRM, 3:MS(LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-04 - Custom Tune (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Normal Tune Page plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "TofMRM.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MRM, 2:MRM, 3:MS(LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_04_CustomTuneHD_ViewedInNormalTunePagePlot_Variant3()
        {
            this.MET_MultipleFunctionSelection_04_CustomTuneHD("Tune Page", "TofMRM.xml", "1:MRM, 2:MRM, 3:MS(LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-04 - Custom Tune (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Normal Tune Page plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "mse_fullhd.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:HDMS(Low CE), 2:HDMS(High CE)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_04_CustomTuneHD_ViewedInNormalTunePagePlot_Variant4()
        {
            this.MET_MultipleFunctionSelection_04_CustomTuneHD("Tune Page", "mse_fullhd.xml", "1:HDMS(Low CE), 2:HDMS(High CE)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-04 - Custom Tune (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Pop-out plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "hdms.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:HDMS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "No")]
        public virtual void MET_MultipleFunctionSelection_04_CustomTuneHD_ViewedInPop_OutPlot_Variant0()
        {
            this.MET_MultipleFunctionSelection_04_CustomTuneHD("Pop-out", "hdms.xml", "1:HDMS", "No", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-04 - Custom Tune (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Pop-out plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "hdmsms.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:HDMSMS")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "No")]
        public virtual void MET_MultipleFunctionSelection_04_CustomTuneHD_ViewedInPop_OutPlot_Variant1()
        {
            this.MET_MultipleFunctionSelection_04_CustomTuneHD("Pop-out", "hdmsms.xml", "1:HDMSMS", "No", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-04 - Custom Tune (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Pop-out plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "HDMRM.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:HDMRM, 2:HDMRM, 3:MS(LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_04_CustomTuneHD_ViewedInPop_OutPlot_Variant2()
        {
            this.MET_MultipleFunctionSelection_04_CustomTuneHD("Pop-out", "HDMRM.xml", "1:HDMRM, 2:HDMRM, 3:MS(LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-04 - Custom Tune (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Pop-out plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 3")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "TofMRM.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:MRM, 2:MRM, 3:MS(LockMass)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_04_CustomTuneHD_ViewedInPop_OutPlot_Variant3()
        {
            this.MET_MultipleFunctionSelection_04_CustomTuneHD("Pop-out", "TofMRM.xml", "1:MRM, 2:MRM, 3:MS(LockMass)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-04 - Custom Tune (HD)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Pop-out plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 4")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Method Type", "mse_fullhd.xml")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Functions", "1:HDMS(Low CE), 2:HDMS(High CE)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Enabled", "Yes")]
        public virtual void MET_MultipleFunctionSelection_04_CustomTuneHD_ViewedInPop_OutPlot_Variant4()
        {
            this.MET_MultipleFunctionSelection_04_CustomTuneHD("Pop-out", "mse_fullhd.xml", "1:HDMS(Low CE), 2:HDMS(High CE)", "Yes", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-05 - Custom Tune - Multiple Plot Type")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        public virtual void MET_MultipleFunctionSelection_05_CustomTune_MultiplePlotType()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MET-MultipleFunctionSelection-05 - Custom Tune - Multiple Plot Type", ((string[])(null)));
#line 186
this.ScenarioSetup(scenarioInfo);
#line 45
this.FeatureBackground();
#line 187
 testRunner.When("an Acquisition multi-function method is run using Acquisition | Custom Tune", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 188
  testRunner.And("this Acquisition is viewed during the recording, within the \'Tune Page\' plot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 189
  testRunner.And("is additionally viewed within a \'Pop-out\' plot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Plot Type 1",
                        "Plot Type 2"});
            table5.AddRow(new string[] {
                        "Tune Page",
                        "Pop-out"});
            table5.AddRow(new string[] {
                        "Pop-out",
                        "Tune Page"});
#line 190
 testRunner.Then("the \'Plot Type 1\' function number can be changed without affecting the \'Plot Type" +
                    " 2\' function selection", ((string)(null)), table5, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-06 - Acquisition Record - Multiple Plot Type")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        public virtual void MET_MultipleFunctionSelection_06_AcquisitionRecord_MultiplePlotType()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MET-MultipleFunctionSelection-06 - Acquisition Record - Multiple Plot Type", ((string[])(null)));
#line 195
this.ScenarioSetup(scenarioInfo);
#line 45
this.FeatureBackground();
#line 196
 testRunner.When("an Acquisition multi-function method is set Recording using Acquisition | Record", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 197
  testRunner.And("this Acquisition is viewed during the recording, within the \'Tune Page\' plot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 198
  testRunner.And("is additionally viewed within a \'Pop-out\' plot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Plot Type 1",
                        "Plot Type 2"});
            table6.AddRow(new string[] {
                        "Tune Page",
                        "Pop-out"});
            table6.AddRow(new string[] {
                        "Pop-out",
                        "Tune Page"});
#line 199
 testRunner.Then("the \'Plot Type 1\' function number can be changed without affecting the \'Plot Type" +
                    " 2\' function selection", ((string)(null)), table6, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void MET_MultipleFunctionSelection_07_CustomTune_ManuallyCreated(string plotType, string plotView, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MET-MultipleFunctionSelection-07 - Custom Tune - Manually Created", exampleTags);
#line 204
this.ScenarioSetup(scenarioInfo);
#line 45
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Setting Name",
                        "Values"});
            table7.AddRow(new string[] {
                        "StartMass",
                        "50"});
            table7.AddRow(new string[] {
                        "EndMass",
                        "2000"});
            table7.AddRow(new string[] {
                        "ScanTime",
                        "5.0"});
#line 205
 testRunner.Given("that the following \'Setting Name\' \'Values\' are manually modified for \'\\Typhoon\\Co" +
                    "nfig\\methods\\ms.xml\'", ((string)(null)), table7, "Given ");
#line 210
  testRunner.And("and the file is Saved as \'ms-modified.xml\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 211
 testRunner.When("the \'ms-modified.xml\' method is run using Acquisition | XML Tuning", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 212
  testRunner.And(string.Format("this Acquisition is viewed during the run, within the \'{0}\'", plotType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 213
 testRunner.Then("an individual \'Function 1\' will be automatically selected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 214
  testRunner.But(string.Format("\'Function 1\' will be disabled in each \'{0}\'", plotView), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "But ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-07 - Custom Tune - Manually Created")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Normal Tune Page plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot View", "MZ")]
        public virtual void MET_MultipleFunctionSelection_07_CustomTune_ManuallyCreated_ViewedInNormalTunePagePlot_Variant0()
        {
            this.MET_MultipleFunctionSelection_07_CustomTune_ManuallyCreated("Tune Page", "MZ", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-07 - Custom Tune - Manually Created")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Normal Tune Page plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot View", "BPI")]
        public virtual void MET_MultipleFunctionSelection_07_CustomTune_ManuallyCreated_ViewedInNormalTunePagePlot_Variant1()
        {
            this.MET_MultipleFunctionSelection_07_CustomTune_ManuallyCreated("Tune Page", "BPI", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-07 - Custom Tune - Manually Created")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Normal Tune Page plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Tune Page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot View", "TIC")]
        public virtual void MET_MultipleFunctionSelection_07_CustomTune_ManuallyCreated_ViewedInNormalTunePagePlot_Variant2()
        {
            this.MET_MultipleFunctionSelection_07_CustomTune_ManuallyCreated("Tune Page", "TIC", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-07 - Custom Tune - Manually Created")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Pop-out plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 0")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot View", "MZ")]
        public virtual void MET_MultipleFunctionSelection_07_CustomTune_ManuallyCreated_ViewedInPop_OutPlot_Variant0()
        {
            this.MET_MultipleFunctionSelection_07_CustomTune_ManuallyCreated("Pop-out", "MZ", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-07 - Custom Tune - Manually Created")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Pop-out plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot View", "BPI")]
        public virtual void MET_MultipleFunctionSelection_07_CustomTune_ManuallyCreated_ViewedInPop_OutPlot_Variant1()
        {
            this.MET_MultipleFunctionSelection_07_CustomTune_ManuallyCreated("Pop-out", "BPI", ((string[])(null)));
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("MET-MultipleFunctionSelection-07 - Custom Tune - Manually Created")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Multiple Function Selection (Live Tune Plot)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("ExampleSetName", "Viewed in Pop-out plot")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Variant 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot Type", "Pop-out")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Plot View", "TIC")]
        public virtual void MET_MultipleFunctionSelection_07_CustomTune_ManuallyCreated_ViewedInPop_OutPlot_Variant2()
        {
            this.MET_MultipleFunctionSelection_07_CustomTune_ManuallyCreated("Pop-out", "TIC", ((string[])(null)));
        }
    }
}
#pragma warning restore
#endregion
